 # Fly.io configuration for frontend deployment
app = "email-sort-app-frontend"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = "5s"

# Resource allocation (frontend needs less resources)
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256